// <auto-generated />
namespace MCDFiscalManager.DataController.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class FDB_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FDB_1));
        
        string IMigrationMetadata.Id
        {
            get { return "202003220948406_FDB_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
